# Generated by Django 3.0 on 2021-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
