# Generated by Django 3.0 on 2021-02-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210222_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='picture',
            new_name='picture_id',
        ),
    ]
